### ISSUE TITLE
suggestion: add `PyPlot.show()` to examples

### ISSUE THREAD

**Issue by WilkAndy** [OrchardLANL/DPFEHM.jl#10]
Currently, the plotting in examples/groundwater_steadystate.jl does not produce a figure.

Feel free to close this issue if you think it's irrelevant.

**Comment by WilkAndy** [comment]
Refs https://github.com/openjournals/joss-reviews/issues/4560

**Comment by omalled** [comment]
I've gone with the `display(fig)` approach to show the figures. In my tests, it works inside a Jupyter notebook and in the terminal with [TerminalExtensions](https://github.com/Keno/TerminalExtensions.jl) (my main approach). Oddly, `PyPlot.show` doesn't show a figure for me. Instead, it prints text in both Jupyter and the terminal. I'm going to leave it as is, but it would be nice to have something that works more universally.
