### ISSUE TITLE
Suggestion: include python as a dependency

### ISSUE THREAD

**Issue by WilkAndy** [OrchardLANL/DPFEHM.jl#11]
You use python/matplotlib for plotting. 

Refs https://github.com/openjournals/joss-reviews/issues/4560

**Comment by omalled** [comment]
I'm only using it in the examples, not the DPFEHM module itself. I've seen people in the Julia community viewing `PyPlot.jl` as a brittle package, so having it as a dependency could create headaches. I've had a few of those myself getting matplotlib to play nicely with other python packages. One option might be having a Manifest.toml file in the examples folder that would make it easy to install all the dependences needed to run the examples. Would that help?

**Comment by WilkAndy** [comment]
The `Manifest.toml` might get stale pretty quickly, do you think?  (Unless you have an automated action to create a clean machine, install dependences, run examples on every pull-request.)  i only mentioned python because it's actually a bit of a beast, eg, i'm quite surprised that the python envivonment i'm using actually works with your code, and i didn't have to downgrade/upgrade something.

Having said this, is it possible to create a list of **julia** packages that you need?  Eg, i'm currently getting a conflict between `AlgebraicMultigrid` and `Preconditioners`.  Obviously, you've managed to install non-conflicting versions of these, but i have no idea.

**Comment by omalled** [comment]
I think the `Manifest.toml` would get stale if there was one for all the examples. But, if there was one for each example, it could be updated whenever the example is updated. Of course, it would be a pain to retroactively create these `Manifest.toml` files, e.g., in the case you mentioned involving `Preconditioners`. Maybe it's worth it to try though.

The packages [`Project.toml`](https://github.com/OrchardLANL/DPFEHM.jl/blob/master/Project.toml) specifies the julia packages that are needed for the core `DPFEHM` functionality. They are automatically installed with `Pkg.add("DPFEHM")`. However, some of the examples require more packages than that. It looks like `Preconditioners` 0.5.0 is compatible with `AlgebraicMultigrid` 0.4.2. `AlgebraicMultigrid` had some breaking changes (`AlgebraicMultigrid.solve` was renamed to `AlgebraicMultigrid._solve`), so the current version of `DPFEHM` doesn't work with `AlgebraicMultigrid` 0.4.2.

I was able to get [this example](https://github.com/OrchardLANL/DPFEHM.jl/blob/master/examples/fracture_network_solver_scaling/getresults.jl) running by doing the following (from a clean directory with all the `.jl` files in that example):
```
]activate .
add AlgebraicMultigrid Preconditioners
include("getresults.jl")
```
This seems to let the package manager find compatible versions of `AlgebraicMultigrid` and `Preconditioners` without worrying about `DPFEHM`'s requirements. Then I guess it is importing the `DPFEHM` that is installed in the main environment?

**Comment by omalled** [comment]
I'm going to go ahead and close this one, since it doesn't seem like including PyCall or PyPlot as a dependency is a good path forward.
