### ISSUE TITLE
tests: specify in readme

### ISSUE THREAD

**Issue by WilkAndy** [OrchardLANL/DPFEHM.jl#12]
Along with the installation instructions, you should state that

`julia runtests.jl`

will verify that the code has been installed and runs correctly.

Refs https://github.com/OrchardLANL/DPFEHM.jl/issues/new

**Comment by omalled** [comment]
I updated the readme to include instructions for testing. I went with the testing capabilities built into Julia's package manager (i.e., `Pkg.test("DPFEHM")`) rather than the `julia runtest.jl` approach. I hope that does the trick!
